---
- name: Add tesseract 4 PPA
  apt_repository: repo='ppa:alex-p/tesseract-ocr'

- name: Install Leptonica
  apt:
    name: libleptonica-dev
    update_cache: yes

- name: Install Tesseract 4
  apt:
    name: tesseract-ocr
    update_cache: yes

- name: Install all tesseract languages
  apt:
    name: tesseract-ocr-all
    update_cache: yes
