---
- name: Update sshd_config
  copy: src=sshd_config dest=/etc/ssh/sshd_config

- name: Bounce sshd
  service:
    name: ssh
    state: restarted

- name: Add ubuntu user into system groups
  user:
    name: ubuntu
    groups: ubuntu,dialout,cdrom,floppy,audio,dip,video,plugdev,netdev
