---
- name: Add Elasticsearch repository key
  apt_key: url=https://artifacts.elastic.co/GPG-KEY-elasticsearch state=present

- name: Ensure Logstash is installed
  apt: deb=https://artifacts.elastic.co/downloads/logstash/logstash-{{ version }}.deb state=present

- name: Install Logstash plugins
  command: "{{ ls_home }}/bin/logstash-plugin install {{ item }}"
  with_items: "{{ plugins | default([]) }}"

- name: Download a plugin gem from an S3 bucket
  command: /usr/local/bin/aws s3 cp s3://{{ s3_bucket }}/{{ s3_prefix }}{{ item }} /tmp/{{ s3_bucket }}/{{ s3_prefix }}{{ item }}
  with_items: "{{ s3_plugins|default([]) }}"

- name: Install a plugin gem from an S3 bucket
  command: "{{ ls_home }}/bin/logstash-plugin install /tmp/{{ s3_bucket }}/{{ s3_prefix }}{{ item }}"
  with_items: "{{ s3_plugins|default([]) }}"
