---
- name: Add Elasticsearch repository key
  apt_key: url=https://artifacts.elastic.co/GPG-KEY-elasticsearch state=present

- name: Ensure Logstash is installed
  apt: deb=https://artifacts.elastic.co/downloads/logstash/logstash-{{ version }}.deb state=present

- name: Install Logstash plugins
  command: "{{ ls_home }}/bin/logstash-plugin install {{ item }}"
  with_items: "{{ plugins | default([]) }}"