---
- name: Install Xvfb
  apt: name=xvfb state=latest

- name: Download Chrome
  get_url: url=https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb dest=/tmp/google-chrome-stable_current_amd64.deb

- name: Install Chrome - ignores errors as expect missing packages
  shell: dpkg -i /tmp/google-chrome-stable_current_amd64.deb
  ignore_errors: yes

- name: Install missing packages for Chrome
  shell: apt-get install -f -y

- name: Download Chromedriver
  shell: wget http://chromedriver.storage.googleapis.com/$(curl https://chromedriver.storage.googleapis.com/LATEST_RELEASE)/chromedriver_linux64.zip /tmp/chromedriver.zip

- name: Unzip Chromedriver
  unarchive: src=/tmp/chromedriver.zip dest=/usr/local/bin/

- name: Enable Chromedriver
  file: path=/usr/local/bin/chromedriver mode=751

- name: Create Xvfb service
  copy: src=xvfb.service dest=/etc/systemd/system/xvfb.service owner=root group=root

- name: Enable Xvfb service
  service: name=xvfb enabled=yes
