---
- name: Install neo4j GPG signing key
  apt_key: url=https://debian.neo4j.org/neotechnology.gpg.key state=present

- name: Add neo4j repository
  apt_repository: repo='deb http://debian.neo4j.org/repo stable/' state=present

- name: Install neo4j
  apt:
    name: neo4j={{ neo4j_version}}
    update_cache: yes