---
- name: Add Elasticsearch repository key
  apt_key: url=https://artifacts.elastic.co/GPG-KEY-elasticsearch state=present

- name: Ensure Kibana is installed - amd64
  apt: deb=https://artifacts.elastic.co/downloads/kibana/kibana-{{ version }}-amd64.deb state=present
  when: ansible_architecture == "x86_64"

- name: Ensure Kibana is installed - arm64
  apt: deb=https://artifacts.elastic.co/downloads/kibana/kibana-{{ version }}-arm64.deb state=present
  when: ansible_architecture == "aarch64"
