---
- name: Download oauth proxy
  unarchive: src=https://github.com/bitly/oauth2_proxy/releases/download/v{{ oauth_version }}/oauth2_proxy-{{ oauth_package_version }}.linux-amd64.go{{ go_version }}.tar.gz dest=/opt remote_src=True

- name: Rename folder
  shell: mv /opt/oauth2_proxy-{{ oauth_package_version }}.linux-amd64.go{{ go_version }} /opt/oauth2_proxy

- name: Create oauth2-proxy group
  group: name=oauth2-proxy

- name: Create oauth2-proxy user
  user: name=oauth2-proxy shell=/bin/false home=/opt/oauth2_proxy createhome=no system=yes group=oauth2-proxy

- name: Create systemd file for oauth proxy
  copy: src={{ systemd_file }} dest=/etc/systemd/system/oauth2-proxy.service

- name: Add sysconfig for oauth proxy
  copy: src=sysconfig-oauth2-proxy dest=/etc/default/oauth2-proxy