---
- name: make directory for script
  file:
    path: /opt/redirect-logs
    state: directory
    mode: 0755

- name: copy script to redirect logs to target location
  copy: src=redirect-logs.sh dest=/opt/redirect-logs/redirect-logs.sh owner=root group=root mode=u+x
