---
- name: Add node source repository
  shell: curl -sL https://deb.nodesource.com/setup_{{node_version}} | bash -
  when: node_full_version is undefined and nodejs_dist_relative_path is undefined

- name: Install Node.js (from nodesource.com)
  apt: name=nodejs state=latest
  when: node_full_version is undefined and nodejs_dist_relative_path is undefined

- name: Download & extract Node.js (from nodejs.org)
  unarchive:
    src: https://nodejs.org/dist/v{{node_full_version}}/node-v{{node_full_version}}-linux-{{architecture}}.tar.gz
    dest: /usr/local
    remote_src: yes
    list_files: yes
    mode: u=rwx,g=rx,o=rx
  when: node_full_version is defined
  register: archive_contents

- name: Store node path
  set_fact:
    node_location: /usr/local/{{archive_contents.files[0]}}bin
  when: node_full_version is defined

- name: Add node symlink in /usr/bin
  file:
    src: "{{ node_location }}/node"
    dest: /usr/bin/node
    state: link
    mode: u=rwx,g=rx,o=rx
  when: node_full_version is defined

- name: Add consistent symlink to node binaries
  file:
    src: "{{ node_location }}"
    dest: /usr/local/node
    state: link
    mode: u=rwx,g=rx,o=rx
  when: node_full_version is defined

- name: Install npm packages
  npm:
    name: "{{ item }}"
    global: yes
  with_items: "{{ packages|default([]) }}"
  environment:
    PATH: "/usr/local/node:{{ lookup('env', 'PATH') }}"
  when: packages is defined and node_full_version is defined
