---
- name: Setup target directory
  file:
    path: /var/lib/cloud/scripts/per-instance
    state: directory
  when:
    - ansible_os_family == "Debian"

- name: Install instance-tag-discovery
  shell: |
    NAME=instance-tag-discovery
    /usr/local/bin/aws s3 cp s3://{{ dist_bucket | quote }}/packages/$NAME/$NAME-linux-{{ deb_arch }} /var/lib/cloud/scripts/per-instance/00-$NAME
    chmod +x /var/lib/cloud/scripts/per-instance/00-$NAME
  when:
    - ansible_os_family == "Debian"

- name: Install devx-logs
  shell: |
    NAME=devx-logs
    /usr/local/bin/aws s3 cp s3://{{ dist_bucket | quote }}/packages/$NAME/$NAME-linux-{{ deb_arch }} /var/lib/cloud/scripts/per-instance/01-$NAME
    chmod +x /var/lib/cloud/scripts/per-instance/01-$NAME
  when:
    - ansible_os_family == "Debian"