---
- name: Install instance-tag-discovery
  ansible.builtin.shell: |
    NAME=instance-tag-discovery-{{ deb_arch }}
    /usr/local/bin/aws s3 cp s3://{{ s3_bucket }}/{{ s3_prefix }}$NAME /var/lib/cloud/scripts/per-instance/00-$NAME
    chmod +x /var/lib/cloud/scripts/per-instance/00-$NAME
  when:
    - ansible_os_family == "Debian"

- name: Install devx-logs
  ansible.builtin.shell: |
    NAME=devx-logs-linux-{{ deb_arch }}
    /usr/local/bin/aws s3 cp s3://{{ s3_bucket }}/{{ s3_prefix }}$NAME /var/lib/cloud/scripts/per-instance/01-$NAME
    chmod +x /var/lib/cloud/scripts/per-instance/01-$NAME
  when:
    - ansible_os_family == "Debian"