---
- name: Download a package from an S3 bucket
  command: /usr/local/bin/aws s3 cp s3://{{ s3_bucket }}/{{ s3_prefix }}instance-tag-discovery-{{ deb_arch }}_1.0-1.deb /tmp/instance-tag-discovery.deb
  when:
    - ansible_os_family == "Debian"

- name: Install cloudwatch agent
  apt:
    deb: /tmp/instance-tag-discovery.deb