---
- name: Fetch AWS Inspector installer script
  get_url: 
    url: https://d1wk0tztpsntt1.cloudfront.net/linux/latest/install 
    dest: /tmp/aws-inspector-installer

- name: Install AWS Inspector
  command: /bin/bash /tmp/aws-inspector-installer

- name: Remove AWS Inspector installer script
  file: 
    path: /tmp/aws-inspector-installer 
    state: absent
