---
- name: Install required dependencies
  apt:
    state: present
    name: [
        'curl',
        'apt-transport-https',
        'lsb-release',
        'gnupg2',
        'jq'
    ]

- name: Add wazuh apt-key
  apt_key: 
    url: https://packages.wazuh.com/key/GPG-KEY-WAZUH
    state: present 

- name: Add wazuh apt repository
  apt_repository: 
    repo: 'deb https://packages.wazuh.com/3.x/apt/ stable main' 
    state: present 
    filename: wazuh 
    update_cache: yes

- name: Install Wazuh Agent
  apt:
    name: wazuh-agent={{ agent_version }}
    state: present
    update_cache: yes

- name: Prevent wazuh-agent from being upgraded to a different version
  dpkg_selections:
    name: wazuh-agent
    selection: hold

- name: Store the password
  shell: |
    SECRET_ARN="{{ secret_id }}"
    REGION=`curl -s http://169.254.169.254/latest/meta-data/placement/availability-zone | sed 's/.$//'`

    aws secretsmanager get-secret-value --secret-id $SECRET_ARN \
       --query SecretString --output text --version-stage AWSCURRENT --region $REGION \
       | jq -r .value > /var/ossec/etc/authd.pass

- name: Inject authentication script
  copy:
    dest: /usr/local/bin/authenticate-with-wazuh-manager.sh
    mode: '0744'
    content: |
      #!/bin/bash -x
      MANAGER_IP="{{ manager_ip }}"
      REGION=`curl -s http://169.254.169.254/latest/meta-data/placement/availability-zone | sed 's/.$//'`

      INSTANCE_ID=`curl -s http://169.254.169.254/latest/meta-data/instance-id`
      FILTERS="Name=resource-id,Values=$INSTANCE_ID Name=resource-type,Values=instance"
      OPTIONS="--query Tags[].Value --output text --region $REGION"

      APP=$(aws ec2 describe-tags --filters $FILTERS Name=key,Values=App $OPTIONS)
      STACK=$(aws ec2 describe-tags --filters $FILTERS Name=key,Values=Stack $OPTIONS)
      STAGE=$(aws ec2 describe-tags --filters $FILTERS Name=key,Values=Stage $OPTIONS)

      cp /var/ossec/etc/ossec.conf /var/ossec/etc/ossec.conf.bak

      sed -i "s/MANAGER_IP/$MANAGER_IP/" /var/ossec/etc/ossec.conf
      sed -i "s/<protocol>udp<\/protocol>/<protocol>tcp<\/protocol>/" /var/ossec/etc/ossec.conf
      cat >> /var/ossec/etc/ossec.conf << EOF
      <ossec_config>
        <labels>
          <label key="aws.app">$APP</label>
          <label key="aws.stack">$STACK</label>
          <label key="aws.stage">$STAGE</label>
        </labels>
      </ossec_config>
      EOF

      # Enroll with manager
      /var/ossec/bin/agent-auth -m $MANAGER_IP -A $INSTANCE_ID

- name: Patch wazuh-agent service to call boot script before starting agent
  lineinfile:
    path: /etc/systemd/system/wazuh-agent.service
    insertbefore: '^ExecStart'
    line: ExecStartPre=/usr/local/bin/authenticate-with-wazuh-manager.sh