---
- name: Uninstall ubuntu docker
  apt:
    name: docker docker-engine docker.io
    state: absent
    force: yes

- name: Install required python packages for 2.7.6
  include_role:
    name: pip-packages
  vars:
    packages:
      - urllib3
      - pyOpenSSL
      - ndg-httpsclient
      - pyasn1

- name: Install required packages
  apt: 
    name:
    - apt-transport-https
    - ca-certificates
    - openssl
    update_cache: yes
    state: present
    force: yes

- name: Add repo key
  apt_key:
    url: "https://download.docker.com/linux/ubuntu/gpg"
    state: present

- name: Add docker.io repo
  apt_repository: repo='deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable' state=present

- name: Install docker
  apt:
    name: docker-ce={{ version }}~ubuntu
    update_cache: yes
    state: present

- name: Create docker group
  group:
    name: docker
